id: P465F9760
initial_creation_type: input
source_metadata:
  title: Magnetizing Series
  language: it
  description: 'Texts on the theme of magnetizing or bringing under one’s control
    (dbang du sdud pa):'
  volume:
    83f2d3de121c4895bde3bbfb02e836cb:
      title: Magnetizing (Wangdü) Prayer
      parent: Prayers
    c8611ce74d3e43758a7e2a7ad590fd43:
      title: 'Wangdü: The Great Cloud of Blessings—The Prayer which Magnetizes All
        that Appears and Exists'
      parent: Prayers
    95634a7c85a441519f64882fc509850b:
      title: 'Swift Enchantment of the Three Realms: A Sādhana of Red Tārā'
      parent: Sādhanas
created_at: '2022-03-01T04:30:45.116063'
last_modified_at: '2022-03-01T04:30:45.116066'
